apikey: "488659919:AAGd3Aj-mRZBg9sTANSvzhuGCdZrY7UOCKM"
tenorkey: "L2BGADS2WNOD"
groups:
    -1001153012150:
        title_reset_delay: 10
    -1001235265562:
        title_prefix: "BGM NA"
        title_reset_delay: 7200
actions:
    kiss:
        keyword: "kiss"
        reply_text: "亲亲你！"
        mention_text: "亲了你一下！"
        anime: True
    hug:
        keyword: "hug"
        reply_text: "抱抱你！"
        mention_text: "抱了你一下！"
        anime: True
    pat:
        keyword: "pat"
        reply_text: "摸摸头"
        mention_text: "摸了摸你的头，表示同情"
        anime: True
    punch:
        keyword: "punch"
        reply_text: "信不信老娘揍你"
        mention_text: "狠狠的揍了你一拳"
        anime: True
    slap:
        keyword: "slap"
        reply_text: "信不信老娘扇你一巴掌"
        mention_text: "狠狠的扇了你一巴掌"
        anime: True
    sleep:
        keyword: "sleep"
        reply_text: "晚安，亲爱的"
        mention_text: "向你道了晚安"
        anime: True

