apikey: "488659919:AAGd3Aj-mRZBg9sTANSvzhuGCdZrY7UOCKM"
tenorkey: "L2BGADS2WNOD"
owner: 272984206
groups:
    -1001153012150:
        title_reset_delay: 10
    -1001235265562:
        title_prefix: "BGM NA"
        title_reset_delay: 7200
actions:
    kiss:
        keyword: "kiss"
        reply_text: "亲亲你！(*￣з￣)"
        mention_text: "亲了你一下！"
        anime: True
    hug:
        keyword: "hug"
        reply_text: "抱抱你！(つ´∀｀)つ"
        mention_text: "抱了你一下！"
        anime: True
    pat:
        keyword: "pat"
        reply_text: "摸摸头(っ´ω`)ﾉ(╥ω╥)"
        mention_text: "摸了摸你的头，表示同情"
        anime: True
    punch:
        keyword: "punch"
        reply_text: "信不信老娘揍你(o￣∇￣)=◯)`ν゜)"
        mention_text: "狠狠的揍了你一拳"
        anime: True
    slap:
        keyword: "slap"
        reply_text: "信不信老娘扇你一巴掌(♯▼皿▼)"
        mention_text: "狠狠的扇了你一巴掌"
        anime: True
    sleep:
        keyword: "sleep"
        reply_text: "晚安，亲爱的(´ω｀*)"
        mention_text: "向你道了晚安"
        anime: True
    tired:
        keyword: "tired"
        reply_text: "很累吧( ´ ▽ ` )ﾉ"
        mention_text: "向你表示他很累"
        anime: True
    peek:
        keyword: "peek"
        reply_text: "盯———— (◉ω◉)"
        mention_text: "悄悄的盯着你"
        anime: True
    mad:
        keyword: "mad"
        reply_text: "生气了？(* ￣︿￣)"
        mention_text: "向你表示很生气"
        anime: True
    smile:
        keyword: "smile"
        reply_text: "露出温柔的微笑(*‘ v`*)"
        mention_text: "向你露出了微笑"
        anime: True
    laugh:
        keyword: "laugh"
        reply_text: "笑得这么开心？o(☆Ф∇Ф☆)o"
        mention_text: "向你发出了欢快的笑声"
        anime: True
    facepalm:
        keyword: "facepalm"
        reply_text: "(=_=)|||"
        mention_text: "向你表示…………无话可说"
        anime: True

