apikey: "KeyHere"
tenorkey: "KeyHere"
owner: 272984206
groups:
    -1001153012150:
        title_reset_delay: 10
    -1001235265562:
        title_prefix: "BGM NA"
        title_reset_delay: 7200
        log_uid: True
        notify_watches_to: -1 # Target ID to send watch notifications
watches:
    count:
        -1001235265562:
            notify: False
    member:
        -1001235265562:
            794359917:
                notify: True
                kick: False # Put uid to kick here
                message: "Executing Unit Test Protocol"
